name: Carlos Rodriguez
author:
  name: Carlos Rodriguez
timezone: America/Los_Angeles
encoding: utf-8
markdown: kramdown
pygments: true
permalink: /:title
exclude: [_scripts,Makefile]
baseurl: ""
paginate: 10
